DROP DATABASE IF EXISTS MEDICO_ORDERS;
CREATE DATABASE IF NOT EXISTS MEDICO_ORDERS;

USE MEDICO_ORDERS;

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    USERID INT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DATEOFBIRTH DATE,
    CREATEDAT TIME
);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS (
    ORDERID INT PRIMARY KEY,
    USERID INT NOT NULL,
    ORDERDATE DATE NOT NULL,
    AMOUNT DECIMAL(65, 2) NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'PENDING',
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS (
    PRODUCTID INT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL,
    CATEGORY VARCHAR(1000) NOT NULL,
    PRICE DECIMAL(65, 2) NOT NULL,
    STOCK INT DEFAULT 0
);

-- Since productid was not orignally in the provided data, we created it, made it a FK and added into it random values between 1 and 101.
ALTER TABLE ORDERS ADD COLUMN PRODUCTID INT;
UPDATE ORDERS SET PRODUCTID = FLOOR(1 + (RAND() * 101));
ALTER TABLE ORDERS ADD FOREIGN KEY(PRODUCTID) REFERENCES PRODUCTS(PRODUCTID);